version: "3.1"
services:
  ucc:
    build: phpdocker/php-fpm
    container_name: ucc
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
